apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfactapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfactapp
  template:
    metadata:
      labels:
        app: myfactapp
    spec:
      containers:
        - name: myfactapp
          image: myfactorialimg
          ports:
            - containerPort: 8080